### PR TITLE
Updated pypy versions to latest

### PR DESCRIPTION
**Pull request by auvipy**

### CODE REVIEW

**Comment by rayrrr** [comment]
@auvipy please check the failed builds and make any needed adjustments.

**Comment by auvipy** [comment]
yup travis saying 7.1 cant be downloaded :D may be it shoud be 7.1.0 or 7.1.1 :D et me check

**Comment by rayrrr** [comment]
@auvipy warning: here be dragons. If you don't _need_ this feature let's just close this PR out. If I don't hear from you in a week or so, I'll do that.

**Comment by rayrrr** [comment]
Closing out as promised.

**Pull request closed without merging**
